# Generated by Django 2.2.6 on 2019-10-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBefore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_description', models.TextField(max_length=2000)),
                ('problem_description', models.TextField(max_length=500)),
                ('general_view', models.ImageField(upload_to='')),
                ('conceptual_design', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('nomination', models.CharField(choices=[('Старый город', 'Старый город'), ('Многоэтажки', 'Многоэтажки'), ('Самый зеленый двор', 'Самый зеленый двор'), ('Самый спортивный', 'Самый спортивный'), ('Лучший двор для детей', 'Лучший двор для детей'), ('Лучший стрит-арт', 'Лучший стрит-арт'), ('Лучший подъезд', 'Лучший подъезд')], default='Старый город', max_length=30)),
                ('adress', models.CharField(max_length=100)),
                ('additional_information', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReformedAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('form_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_photos', to='odessa_courtyards.FormBefore')),
            ],
        ),
    ]
