# Generated by Django 2.2.6 on 2019-10-19 13:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odessa_courtyards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('registration_date', models.DateField(default=datetime.datetime(2019, 10, 19, 16, 3, 57, 829075))),
            ],
        ),
        migrations.CreateModel(
            name='FormAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_view', models.ImageField(upload_to='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odessa_courtyards.Member')),
            ],
        ),
        migrations.AddField(
            model_name='reformedareas',
            name='form_after',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reformed_photos', to='odessa_courtyards.FormAfter'),
        ),
    ]
