# Generated by Django 2.2.6 on 2019-10-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odessa_courtyards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formafter',
            name='done_work_description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='formbefore',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='odessa_courtyards.Member'),
        ),
        migrations.AlterField(
            model_name='formafter',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='odessa_courtyards.Member'),
        ),
    ]
