# Generated by Django 2.2.6 on 2019-10-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odessa_courtyards', '0002_auto_20191019_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formafter',
            name='general_view',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formbefore',
            name='conceptual_design',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formbefore',
            name='plan_description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='formbefore',
            name='problem_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
