# Generated by Django 2.2.6 on 2019-10-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odessa_courtyards', '0003_auto_20191020_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbefore',
            name='conceptual_design',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formbefore',
            name='general_view',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
